package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

/**
 * Brand generated by hbm2java
 */
public class Brand implements java.io.Serializable {

	private BrandId id;

	public Brand() {
	}

	public Brand(BrandId id) {
		this.id = id;
	}

	public BrandId getId() {
		return this.id;
	}

	public void setId(BrandId id) {
		this.id = id;
	}

}
