package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

/**
 * BrandId generated by hbm2java
 */
public class BrandId implements java.io.Serializable {

	private int code;
	private String name;

	public BrandId() {
	}

	public BrandId(int code, String name) {
		this.code = code;
		this.name = name;
	}

	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BrandId))
			return false;
		BrandId castOther = (BrandId) other;

		return (this.getCode() == castOther.getCode())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCode();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
