package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer code;
	private String name;
	private String address;
	private String contactNumber;
	private String smsNotificationNumber;

	public Customer() {
	}

	public Customer(String name, String address, String contactNumber, String smsNotificationNumber) {
		this.name = name;
		this.address = address;
		this.contactNumber = contactNumber;
		this.smsNotificationNumber = smsNotificationNumber;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getSmsNotificationNumber() {
		return this.smsNotificationNumber;
	}

	public void setSmsNotificationNumber(String smsNotificationNumber) {
		this.smsNotificationNumber = smsNotificationNumber;
	}

}
