package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private Integer code;
	private Category category;
	private String name;
	private String shortName;
	private Set itemUnitOfMeasurements = new HashSet(0);

	public Item() {
	}

	public Item(Category category, String name, String shortName) {
		this.category = category;
		this.name = name;
		this.shortName = shortName;
	}

	public Item(Category category, String name, String shortName, Set itemUnitOfMeasurements) {
		this.category = category;
		this.name = name;
		this.shortName = shortName;
		this.itemUnitOfMeasurements = itemUnitOfMeasurements;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public Set getItemUnitOfMeasurements() {
		return this.itemUnitOfMeasurements;
	}

	public void setItemUnitOfMeasurements(Set itemUnitOfMeasurements) {
		this.itemUnitOfMeasurements = itemUnitOfMeasurements;
	}

}
