package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ItemUnitOfMeasurement generated by hbm2java
 */
public class ItemUnitOfMeasurement implements java.io.Serializable {

	private ItemUnitOfMeasurementId id;
	private Item item;
	private UnitOfMeasurement unitOfMeasurement;
	private int contentUnitOfMeasurementCode;
	private int contentQuantity;
	private BigDecimal rate;

	public ItemUnitOfMeasurement() {
	}

	public ItemUnitOfMeasurement(ItemUnitOfMeasurementId id, Item item, UnitOfMeasurement unitOfMeasurement,
			int contentUnitOfMeasurementCode, int contentQuantity, BigDecimal rate) {
		this.id = id;
		this.item = item;
		this.unitOfMeasurement = unitOfMeasurement;
		this.contentUnitOfMeasurementCode = contentUnitOfMeasurementCode;
		this.contentQuantity = contentQuantity;
		this.rate = rate;
	}

	public ItemUnitOfMeasurementId getId() {
		return this.id;
	}

	public void setId(ItemUnitOfMeasurementId id) {
		this.id = id;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public UnitOfMeasurement getUnitOfMeasurement() {
		return this.unitOfMeasurement;
	}

	public void setUnitOfMeasurement(UnitOfMeasurement unitOfMeasurement) {
		this.unitOfMeasurement = unitOfMeasurement;
	}

	public int getContentUnitOfMeasurementCode() {
		return this.contentUnitOfMeasurementCode;
	}

	public void setContentUnitOfMeasurementCode(int contentUnitOfMeasurementCode) {
		this.contentUnitOfMeasurementCode = contentUnitOfMeasurementCode;
	}

	public int getContentQuantity() {
		return this.contentQuantity;
	}

	public void setContentQuantity(int contentQuantity) {
		this.contentQuantity = contentQuantity;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

}
