package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * OperatorPurchaseOrderMapping generated by hbm2java
 */
public class OperatorPurchaseOrderMapping implements java.io.Serializable {

	private Long referenceNumber;
	private ShopOperator shopOperator;
	private Date mappingDate;
	private Date mappingTime;
	private Long purchaseOrderReferenceNumber;
	private Character processStatus;

	public OperatorPurchaseOrderMapping() {
	}

	public OperatorPurchaseOrderMapping(ShopOperator shopOperator, Date mappingDate, Date mappingTime,
			Long purchaseOrderReferenceNumber, Character processStatus) {
		this.shopOperator = shopOperator;
		this.mappingDate = mappingDate;
		this.mappingTime = mappingTime;
		this.purchaseOrderReferenceNumber = purchaseOrderReferenceNumber;
		this.processStatus = processStatus;
	}

	public Long getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(Long referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public ShopOperator getShopOperator() {
		return this.shopOperator;
	}

	public void setShopOperator(ShopOperator shopOperator) {
		this.shopOperator = shopOperator;
	}

	public Date getMappingDate() {
		return this.mappingDate;
	}

	public void setMappingDate(Date mappingDate) {
		this.mappingDate = mappingDate;
	}

	public Date getMappingTime() {
		return this.mappingTime;
	}

	public void setMappingTime(Date mappingTime) {
		this.mappingTime = mappingTime;
	}

	public Long getPurchaseOrderReferenceNumber() {
		return this.purchaseOrderReferenceNumber;
	}

	public void setPurchaseOrderReferenceNumber(Long purchaseOrderReferenceNumber) {
		this.purchaseOrderReferenceNumber = purchaseOrderReferenceNumber;
	}

	public Character getProcessStatus() {
		return this.processStatus;
	}

	public void setProcessStatus(Character processStatus) {
		this.processStatus = processStatus;
	}

}
