package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ProcessedPurchaseOrder generated by hbm2java
 */
public class ProcessedPurchaseOrder implements java.io.Serializable {

	private long referenceNumber;
	private ShopOperator shopOperator;
	private Date mappingDate;
	private Date mappingTime;
	private long purchaseOrderReferenceNumber;
	private char processStatus;
	private Date completionDate;
	private Date completionTime;

	public ProcessedPurchaseOrder() {
	}

	public ProcessedPurchaseOrder(long referenceNumber, ShopOperator shopOperator, Date mappingDate, Date mappingTime,
			long purchaseOrderReferenceNumber, char processStatus, Date completionDate, Date completionTime) {
		this.referenceNumber = referenceNumber;
		this.shopOperator = shopOperator;
		this.mappingDate = mappingDate;
		this.mappingTime = mappingTime;
		this.purchaseOrderReferenceNumber = purchaseOrderReferenceNumber;
		this.processStatus = processStatus;
		this.completionDate = completionDate;
		this.completionTime = completionTime;
	}

	public long getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(long referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public ShopOperator getShopOperator() {
		return this.shopOperator;
	}

	public void setShopOperator(ShopOperator shopOperator) {
		this.shopOperator = shopOperator;
	}

	public Date getMappingDate() {
		return this.mappingDate;
	}

	public void setMappingDate(Date mappingDate) {
		this.mappingDate = mappingDate;
	}

	public Date getMappingTime() {
		return this.mappingTime;
	}

	public void setMappingTime(Date mappingTime) {
		this.mappingTime = mappingTime;
	}

	public long getPurchaseOrderReferenceNumber() {
		return this.purchaseOrderReferenceNumber;
	}

	public void setPurchaseOrderReferenceNumber(long purchaseOrderReferenceNumber) {
		this.purchaseOrderReferenceNumber = purchaseOrderReferenceNumber;
	}

	public char getProcessStatus() {
		return this.processStatus;
	}

	public void setProcessStatus(char processStatus) {
		this.processStatus = processStatus;
	}

	public Date getCompletionDate() {
		return this.completionDate;
	}

	public void setCompletionDate(Date completionDate) {
		this.completionDate = completionDate;
	}

	public Date getCompletionTime() {
		return this.completionTime;
	}

	public void setCompletionTime(Date completionTime) {
		this.completionTime = completionTime;
	}

}
