package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * PurchaseOrderItem generated by hbm2java
 */
public class PurchaseOrderItem implements java.io.Serializable {

	private long referenceNumber;
	private PurchaseOrder purchaseOrder;
	private int itemCode;
	private int unitOfMeasurementCode;
	private BigDecimal quantity;
	private BigDecimal rate;
	private char orderStatus;
	private String comment;

	public PurchaseOrderItem() {
	}

	public PurchaseOrderItem(long referenceNumber, PurchaseOrder purchaseOrder, int itemCode, int unitOfMeasurementCode,
			BigDecimal quantity, BigDecimal rate, char orderStatus, String comment) {
		this.referenceNumber = referenceNumber;
		this.purchaseOrder = purchaseOrder;
		this.itemCode = itemCode;
		this.unitOfMeasurementCode = unitOfMeasurementCode;
		this.quantity = quantity;
		this.rate = rate;
		this.orderStatus = orderStatus;
		this.comment = comment;
	}

	public long getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(long referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public PurchaseOrder getPurchaseOrder() {
		return this.purchaseOrder;
	}

	public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}

	public int getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(int itemCode) {
		this.itemCode = itemCode;
	}

	public int getUnitOfMeasurementCode() {
		return this.unitOfMeasurementCode;
	}

	public void setUnitOfMeasurementCode(int unitOfMeasurementCode) {
		this.unitOfMeasurementCode = unitOfMeasurementCode;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public char getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(char orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
