package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseOrder generated by hbm2java
 */
public class PurchaseOrder implements java.io.Serializable {

	private long referenceNumber;
	private Date dateOfOrder;
	private Date timeOfOrder;
	private Integer customerCode;
	private Character orderStatus;
	private Set purchaseOrderItems = new HashSet(0);

	public PurchaseOrder() {
	}

	public PurchaseOrder(long referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public PurchaseOrder(long referenceNumber, Date dateOfOrder, Date timeOfOrder, Integer customerCode,
			Character orderStatus, Set purchaseOrderItems) {
		this.referenceNumber = referenceNumber;
		this.dateOfOrder = dateOfOrder;
		this.timeOfOrder = timeOfOrder;
		this.customerCode = customerCode;
		this.orderStatus = orderStatus;
		this.purchaseOrderItems = purchaseOrderItems;
	}

	public long getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(long referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public Date getDateOfOrder() {
		return this.dateOfOrder;
	}

	public void setDateOfOrder(Date dateOfOrder) {
		this.dateOfOrder = dateOfOrder;
	}

	public Date getTimeOfOrder() {
		return this.timeOfOrder;
	}

	public void setTimeOfOrder(Date timeOfOrder) {
		this.timeOfOrder = timeOfOrder;
	}

	public Integer getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(Integer customerCode) {
		this.customerCode = customerCode;
	}

	public Character getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Character orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Set getPurchaseOrderItems() {
		return this.purchaseOrderItems;
	}

	public void setPurchaseOrderItems(Set purchaseOrderItems) {
		this.purchaseOrderItems = purchaseOrderItems;
	}

}
