package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ShopOperator generated by hbm2java
 */
public class ShopOperator implements java.io.Serializable {

	private String username;
	private String password;
	private String passwordKey;
	private boolean isAdminstrator;
	private String name;
	private Set operatorPurchaseOrderMappings = new HashSet(0);
	private Set processedPurchaseOrders = new HashSet(0);

	public ShopOperator() {
	}

	public ShopOperator(String username, String password, String passwordKey, boolean isAdminstrator, String name) {
		this.username = username;
		this.password = password;
		this.passwordKey = passwordKey;
		this.isAdminstrator = isAdminstrator;
		this.name = name;
	}

	public ShopOperator(String username, String password, String passwordKey, boolean isAdminstrator, String name,
			Set operatorPurchaseOrderMappings, Set processedPurchaseOrders) {
		this.username = username;
		this.password = password;
		this.passwordKey = passwordKey;
		this.isAdminstrator = isAdminstrator;
		this.name = name;
		this.operatorPurchaseOrderMappings = operatorPurchaseOrderMappings;
		this.processedPurchaseOrders = processedPurchaseOrders;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordKey() {
		return this.passwordKey;
	}

	public void setPasswordKey(String passwordKey) {
		this.passwordKey = passwordKey;
	}

	public boolean isIsAdminstrator() {
		return this.isAdminstrator;
	}

	public void setIsAdminstrator(boolean isAdminstrator) {
		this.isAdminstrator = isAdminstrator;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getOperatorPurchaseOrderMappings() {
		return this.operatorPurchaseOrderMappings;
	}

	public void setOperatorPurchaseOrderMappings(Set operatorPurchaseOrderMappings) {
		this.operatorPurchaseOrderMappings = operatorPurchaseOrderMappings;
	}

	public Set getProcessedPurchaseOrders() {
		return this.processedPurchaseOrders;
	}

	public void setProcessedPurchaseOrders(Set processedPurchaseOrders) {
		this.processedPurchaseOrders = processedPurchaseOrders;
	}

}
