package com.thinking.machines.egrocery.hibernate;
// Generated 16 Jan, 2018 9:36:23 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UnitOfMeasurement generated by hbm2java
 */
public class UnitOfMeasurement implements java.io.Serializable {

	private Integer code;
	private String name;
	private Set itemUnitOfMeasurements = new HashSet(0);

	public UnitOfMeasurement() {
	}

	public UnitOfMeasurement(String name) {
		this.name = name;
	}

	public UnitOfMeasurement(String name, Set itemUnitOfMeasurements) {
		this.name = name;
		this.itemUnitOfMeasurements = itemUnitOfMeasurements;
	}

	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItemUnitOfMeasurements() {
		return this.itemUnitOfMeasurements;
	}

	public void setItemUnitOfMeasurements(Set itemUnitOfMeasurements) {
		this.itemUnitOfMeasurements = itemUnitOfMeasurements;
	}

}
